# Generated by Django 5.0.3 on 2024-03-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_preco_alter_produtos_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
